spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://
    username: postgres
    password: senha
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      show-sql: true
  server:
    port: ${PORT:8080}
